import os
import time
import json
import logging
import socket
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Any, Optional

# Force IPv4 resolution for Dhan API so Dhan checks the registered IPv4 static IP instead of local IPv6
try:
    from urllib3.util import connection
    def _force_ipv4():
        return socket.AF_INET
    connection.allowed_gai_family = _force_ipv4
except Exception:
    pass

logger = logging.getLogger(__name__)
IST = timezone(timedelta(hours=5, minutes=30))

CONFIG_FILE = os.path.join(os.path.dirname(__file__), "dhan_config.json")
SESSION_FILE = os.path.join(os.path.dirname(__file__), "..", "..", ".dhan_session.json")
ORDER_TRACKER_FILE = os.path.join(os.path.dirname(__file__), "order_sl_tracker.json")

class DhanTradeService:
    def __init__(self):
        self.client_id: Optional[str] = None
        self.access_token: Optional[str] = None
        self.is_connected: bool = False
        self.account_name: str = "Dhan Trading Account"
        self.cash_balance: float = 0.0
        self.dhan_client = None
        self.load_credentials()

    def load_credentials(self):
        """Loads client ID and access token from active session or config."""
        self.client_id = os.getenv("DHAN_CLIENT_ID")
        self.access_token = os.getenv("DHAN_ACCESS_TOKEN")

        # 1. Try active session file (auto-generated by daily TOTP or manual login)
        if os.path.exists(SESSION_FILE):
            try:
                with open(SESSION_FILE, "r") as f:
                    s_data = json.load(f)
                    self.client_id = s_data.get("client_id") or self.client_id
                    self.access_token = s_data.get("access_token") or self.access_token
            except Exception as e:
                logger.warning(f"Error loading Dhan session file: {e}")

        # 2. Try explicit trade config file if not in session
        if not self.client_id and os.path.exists(CONFIG_FILE):
            try:
                with open(CONFIG_FILE, "r") as f:
                    data = json.load(f)
                    self.client_id = data.get("client_id") or self.client_id
                    self.access_token = data.get("access_token") or self.access_token
            except Exception as e:
                logger.warning(f"Error loading Dhan config file: {e}")

        if self.client_id and self.access_token:
            self._init_dhan_client()

    def save_credentials(self, client_id: str, access_token: str) -> Dict[str, Any]:
        """Manually saves or updates Dhan API credentials."""
        self.client_id = client_id.strip()
        self.access_token = access_token.strip()
        
        try:
            with open(CONFIG_FILE, "w") as f:
                json.dump({
                    "client_id": self.client_id,
                    "access_token": self.access_token,
                    "updated_at": datetime.now(IST).isoformat()
                }, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to save Dhan credentials: {e}")

        self._init_dhan_client()

        # Automatically check and register IP on Dhan when credentials are saved
        try:
            from app.engine.dhan_ip_service import dhan_ip_service
            dhan_ip_service.check_and_sync_ip(force=True)
        except Exception as e_ip:
            logger.warning(f"Could not auto-sync IP on save credentials: {e_ip}")

        return self.verify_connection()

    def _init_dhan_client(self):
        """Initializes DhanHQ SDK client using DhanContext (v2 architecture)."""
        try:
            from dhanhq import dhanhq, DhanContext
            try:
                ctx = DhanContext(self.client_id, self.access_token)
                self.dhan_client = dhanhq(ctx)
            except Exception:
                self.dhan_client = dhanhq(self.client_id, self.access_token)
            logger.info(f"DhanHQ trading client initialized for Client ID: {self.client_id[:4]}***")
        except Exception as e:
            logger.warning(f"Failed to initialize dhanhq trading client: {e}")
            self.dhan_client = None

    def verify_connection(self) -> Dict[str, Any]:
        """Verifies connection with Dhan and returns genuine live balance."""
        if not self.client_id or not self.access_token:
            return {
                "connected": False,
                "message": "Dhan credentials not configured. Please enter Client ID and Access Token in Settings.",
                "client_id": None,
                "cash_balance": 0.0,
                "available_margin": 0.0
            }

        if not self.dhan_client:
            self._init_dhan_client()

        if self.dhan_client:
            try:
                resp = self.dhan_client.get_fund_limits()
                if resp.get("status") == "success" and isinstance(resp.get("data"), dict):
                    data = resp.get("data", {})
                    avail_bal = float(data.get("availabelBalance") or data.get("availableBalance") or data.get("sodLimit") or 0.0)
                    self.cash_balance = avail_bal
                    self.is_connected = True
                    return {
                        "connected": True,
                        "message": "Connected to Dhan Live Trading API.",
                        "client_id": self.client_id,
                        "cash_balance": self.cash_balance,
                        "available_margin": self.cash_balance
                    }
                else:
                    err_msg = str(resp.get("remarks") or resp.get("message") or "Failed to authenticate with Dhan.")
                    logger.warning(f"Dhan get_fund_limits failed: {err_msg}")
                    return {
                        "connected": False,
                        "message": f"Dhan token validation failed: {err_msg}",
                        "client_id": self.client_id,
                        "cash_balance": 0.0,
                        "available_margin": 0.0
                    }
            except Exception as e:
                logger.warning(f"Dhan verify_connection error: {e}")
                return {
                    "connected": False,
                    "message": f"Dhan API error: {str(e)}",
                    "client_id": self.client_id,
                    "cash_balance": 0.0,
                    "available_margin": 0.0
                }

        return {
            "connected": False,
            "message": "DhanHQ client could not be initialized.",
            "client_id": self.client_id,
            "cash_balance": 0.0,
            "available_margin": 0.0
        }

    # ---------------------------------------------------------
    # 1. DEMAT HOLDINGS (100% Real from Dhan)
    # ---------------------------------------------------------
    def get_holdings(self) -> List[Dict[str, Any]]:
        """Retrieves genuine Demat equity holdings directly from Dhan."""
        if not self.dhan_client:
            self._init_dhan_client()

        if not self.dhan_client:
            return []

        try:
            resp = self.dhan_client.get_holdings()
            if resp.get("status") == "success" and isinstance(resp.get("data"), list):
                holdings_raw = resp.get("data", [])
                results = []
                for h in holdings_raw:
                    qty = int(h.get("totalQty", 0))
                    if qty <= 0:
                        continue
                    cost = float(h.get("avgCostPrice", 0.0))
                    cmp_price = float(h.get("lastTradedPrice", cost))
                    invested = round(qty * cost, 2)
                    cur_val = round(qty * cmp_price, 2)
                    pnl = round(cur_val - invested, 2)
                    pnl_pct = round((pnl / invested) * 100, 2) if invested > 0 else 0.0

                    results.append({
                        "symbol": h.get("tradingSymbol", "STOCK"),
                        "company_name": h.get("companyName") or h.get("tradingSymbol", ""),
                        "quantity": qty,
                        "buy_avg": cost,
                        "avg_cost_price": cost,
                        "cmp": cmp_price,
                        "current_price": cmp_price,
                        "invested_value": invested,
                        "invested_amount": invested,
                        "current_value": cur_val,
                        "total_pnl": pnl,
                        "total_pnl_pct": pnl_pct,
                        "dp_qty": h.get("dpQty", qty),
                        "exchange": h.get("exchangeSegment", "NSE")
                    })
                return results
            else:
                # E.g. DH-1111: No holdings available
                return []
        except Exception as e:
            logger.error(f"Error fetching Dhan holdings: {e}")
            return []

    # ---------------------------------------------------------
    # 2. OPEN POSITIONS (100% Real from Dhan)
    # ---------------------------------------------------------
    def get_open_positions(self) -> List[Dict[str, Any]]:
        """Retrieves genuine active intraday/carryforward positions from Dhan."""
        if not self.dhan_client:
            self._init_dhan_client()

        if not self.dhan_client:
            return []

        tracker = self._load_order_sl_tracker()

        try:
            resp = self.dhan_client.get_positions()
            if resp.get("status") == "success" and isinstance(resp.get("data"), list):
                raw_positions = resp.get("data", [])
                active_pos = [p for p in raw_positions if int(p.get("netQty", 0)) != 0]

                # Fetch genuine live ticks from Dhan for open positions
                sec_map = {}
                if active_pos:
                    nse_ids = []
                    for p in active_pos:
                        s_id = p.get("securityId")
                        if s_id:
                            try:
                                nse_ids.append(int(s_id))
                            except Exception:
                                pass
                    if nse_ids:
                        try:
                            tick_resp = self.dhan_client.ticker_data(securities={"NSE_EQ": nse_ids})
                            if tick_resp.get("status") == "success":
                                sec_data = tick_resp.get("data", {}).get("data", {}).get("NSE_EQ", {})
                                for s_id_str, d in sec_data.items():
                                    if "last_price" in d:
                                        sec_map[str(s_id_str)] = float(d["last_price"])
                        except Exception as e:
                            logger.warning(f"Failed to fetch Dhan ticker_data for positions: {e}")

                results = []
                for p in active_pos:
                    net_qty = int(p.get("netQty", 0))
                    sym = p.get("tradingSymbol", "STOCK")
                    sec_id_str = str(p.get("securityId", ""))
                    buy_avg = float(p.get("buyAvg", 0.0) or p.get("costPrice", 0.0))
                    unrealized = float(p.get("unrealizedProfit", 0.0))

                    # 1. Primary: Live Dhan ticker feed
                    if sec_id_str in sec_map and sec_map[sec_id_str] > 0:
                        cmp_val = sec_map[sec_id_str]
                    # 2. Secondary: calculate from Dhan real-time unrealizedProfit
                    elif net_qty != 0 and unrealized != 0:
                        cmp_val = round(buy_avg + (unrealized / net_qty), 2)
                    else:
                        cmp_val = buy_avg

                    # Calculate live P&L based on genuine real-time CMP
                    live_pnl = round((cmp_val - buy_avg) * net_qty, 2) if (net_qty != 0 and buy_avg > 0) else unrealized
                    unrealized_pct = round(((cmp_val / buy_avg) - 1.0) * 100, 2) if buy_avg > 0 else 0.0

                    # Check if there is an exchange Stop-Loss attached from our tracker
                    sl_info = tracker.get(sym, {})

                    results.append({
                        "position_id": f"pos_{sym}_{p.get('securityId', '')}",
                        "symbol": sym,
                        "company_name": sym,
                        "exchange_segment": p.get("exchangeSegment", "NSE_EQ"),
                        "quantity": abs(net_qty),
                        "transaction_type": "BUY" if net_qty > 0 else "SELL",
                        "buy_price": buy_avg,
                        "buy_avg": buy_avg,
                        "buy_avg_price": buy_avg,
                        "cmp": cmp_val,
                        "current_price": cmp_val,
                        "tentative_pnl": live_pnl,
                        "unrealized_pnl": live_pnl,
                        "tentative_pnl_pct": unrealized_pct,
                        "unrealized_pnl_pct": unrealized_pct,
                        "product_type": p.get("productType", "INTRADAY"),
                        "security_id": p.get("securityId", ""),
                        "stop_loss_1": sl_info.get("stop_loss_1"),
                        "stop_loss_2": sl_info.get("stop_loss_2"),
                        "sl_order_id": sl_info.get("sl_order_id"),
                        "target_price": sl_info.get("target_price"),
                        "target_order_id": sl_info.get("target_order_id"),
                        "status": "OPEN"
                    })
                return results
            else:
                return []
        except Exception as e:
            logger.error(f"Error fetching Dhan positions: {e}")
            return []

    # ---------------------------------------------------------
    # 3. ORDER BOOK (100% Real from Dhan)
    # ---------------------------------------------------------
    def get_orders(self) -> List[Dict[str, Any]]:
        """Retrieves genuine orders list placed in today's session directly from Dhan."""
        if not self.dhan_client:
            self._init_dhan_client()

        if not self.dhan_client:
            return []

        try:
            resp = self.dhan_client.get_order_list()
            raw_orders = resp.get("data", []) if (resp.get("status") == "success" and isinstance(resp.get("data"), list)) else []

            # Also merge Dhan Super Orders (Bracket Orders)
            try:
                super_resp = self.dhan_client.get_super_order_list()
                if super_resp.get("status") == "success" and isinstance(super_resp.get("data"), list):
                    raw_orders.extend(super_resp.get("data", []))
            except Exception as e_s:
                logger.warning(f"Failed to fetch super orders list: {e_s}")

            if raw_orders:
                # Fetch live ticks from Dhan for distinct order security IDs
                sec_map = {}
                nse_ids = []
                for o in raw_orders:
                    s_id = o.get("securityId")
                    if s_id:
                        try:
                            s_int = int(s_id)
                            if s_int not in nse_ids:
                                nse_ids.append(s_int)
                        except Exception:
                            pass
                if nse_ids:
                    try:
                        tick_resp = self.dhan_client.ticker_data(securities={"NSE_EQ": nse_ids})
                        if tick_resp.get("status") == "success":
                            sec_data = tick_resp.get("data", {}).get("data", {}).get("NSE_EQ", {})
                            for s_id_str, d in sec_data.items():
                                if "last_price" in d:
                                    sec_map[str(s_id_str)] = float(d["last_price"])
                    except Exception as e:
                        logger.warning(f"Failed to fetch Dhan ticker_data for orders: {e}")

                results = []
                for ord_item in raw_orders:
                    qty = int(ord_item.get("quantity", 0))
                    price = float(ord_item.get("price", 0.0))
                    status = ord_item.get("orderStatus", "PENDING").upper()
                    sec_id_str = str(ord_item.get("securityId", ""))
                    cmp_val = sec_map.get(sec_id_str, price if price > 0 else 0.0)
                    rejection_reason = ord_item.get("omsErrorDescription") or ord_item.get("rejectionReason") or ""
                    
                    results.append({
                        "order_id": str(ord_item.get("orderId", "")),
                        "symbol": ord_item.get("tradingSymbol", "STOCK"),
                        "exchange_segment": ord_item.get("exchangeSegment", "NSE_EQ"),
                        "transaction_type": ord_item.get("transactionType", "BUY"),
                        "quantity": qty,
                        "price": price,
                        "cmp": cmp_val,
                        "current_price": cmp_val,
                        "total_amount": round(qty * price, 2) if price > 0 else 0.0,
                        "order_type": ord_item.get("orderType", "MARKET"),
                        "product_type": ord_item.get("productType", "INTRADAY"),
                        "status": status,
                        "status_label": ord_item.get("orderStatus", "Placed"),
                        "trigger_price": float(ord_item.get("triggerPrice", 0.0)),
                        "placed_at": ord_item.get("createTime") or ord_item.get("updateTime") or "Today",
                        "rejection_reason": rejection_reason
                    })
                return results
            else:
                return []
        except Exception as e:
            logger.error(f"Error fetching Dhan orders: {e}")
            return []

    def cancel_order(self, order_id: str) -> Dict[str, Any]:
        """Cancels a pending order directly on Dhan exchange."""
        if not self.dhan_client:
            self._init_dhan_client()

        if not self.dhan_client:
            raise RuntimeError("Dhan trading client is not connected.")

        logger.info(f"Submitting order cancellation to Dhan for Order ID: {order_id}")
        resp = self.dhan_client.cancel_order(order_id=order_id)
        logger.info(f"Dhan cancel_order response: {resp}")

        if resp.get("status") != "success":
            err = str(resp.get("remarks") or resp.get("message") or "Order cancellation rejected by Dhan.")
            raise RuntimeError(f"Cancel failed: {err}")

        # If this order is in our tracker, update tracker
        tracker = self._load_order_sl_tracker()
        modified = False
        for sym, data in tracker.items():
            if data.get("sl_order_id") == order_id:
                data["sl_order_id"] = None
                modified = True
            if data.get("target_order_id") == order_id:
                data["target_order_id"] = None
                modified = True
        if modified:
            self._save_order_sl_tracker(tracker)

        return {
            "status": "SUCCESS",
            "message": f"Order {order_id} successfully cancelled on Dhan exchange.",
            "order_id": order_id
        }

    # ---------------------------------------------------------
    # 4. ORDER PLACEMENT WITH REAL SERVER-SIDE STOP LOSS
    # ---------------------------------------------------------
    def place_buy_order(
        self,
        symbol: str,
        quantity: int,
        price: float,
        stop_loss_1: float,
        conditional_stop_2: Optional[float] = None,
        target_price: Optional[float] = None,
        security_id: Optional[str] = None,
        exchange_segment: str = "NSE_EQ",
        product_type: str = "INTRADAY",
        order_type: str = "LIMIT",
        company_name: str = "",
        bse_scrip: str = ""
    ) -> Dict[str, Any]:
        """
        Executes real BUY order on Dhan, and immediately places exchange-level
        Stop-Loss Order (SL-M) with Dhan so your downside is 100% protected
        even if internet or power drops.
        """
        if not self.dhan_client:
            self._init_dhan_client()

        if not self.dhan_client:
            raise RuntimeError("Dhan trading client is not connected. Please verify credentials in Settings.")

        # Check and auto-sync dynamic IP if needed
        try:
            from app.engine.dhan_ip_service import dhan_ip_service
            dhan_ip_service.check_and_sync_ip()
        except Exception as _e:
            logger.warning(f"Could not check dynamic IP before trade: {_e}")

        sym = symbol.upper().strip()
        sec_id = security_id or bse_scrip

        # Auto-resolve security ID from universe catalog if missing
        if not sec_id:
            from app.engine.dhan_provider import dhan_provider
            stk = dhan_provider.stocks_cache.get(sym, {})
            sec_id = str(stk.get("nse_id") or stk.get("bse_id") or "")
            if stk.get("nse_id"):
                exchange_segment = "NSE_EQ"
            elif stk.get("bse_id"):
                exchange_segment = "BSE_EQ"

        if not sec_id:
            raise RuntimeError(f"Could not resolve Dhan Security ID for {sym}. Please check symbol.")

        # Map Dhan SDK constants
        dhan_prod = self.dhan_client.INTRA if product_type == "INTRADAY" else self.dhan_client.CNC
        dhan_order_type = self.dhan_client.MARKET if order_type == "MARKET" else self.dhan_client.LIMIT
        dhan_exch = self.dhan_client.NSE if "NSE" in exchange_segment.upper() else self.dhan_client.BSE

        logger.info(f"Submitting live BUY order to Dhan: {sym} Qty={quantity} SecID={sec_id} Exch={exchange_segment}")

        # Round limit price, stop loss, and target to 0.05 tick size
        # If user selected MARKET, we use the passed CMP rounded to 0.05 tick size as entry price
        # for Dhan Super Order (Bracket Order) so BOTH custom Stop-Loss and custom Exit Target
        # are submitted directly to the exchange.
        entry_price = round(round(float(price) / 0.05) * 0.05, 2) if price and float(price) > 0 else 0.0
        target_val = round(round(float(target_price) / 0.05) * 0.05, 2) if target_price and float(target_price) > 0 else 0.0
        sl_val = round(round(float(stop_loss_1) / 0.05) * 0.05, 2) if stop_loss_1 and float(stop_loss_1) > 0 else 0.0

        logger.info(
            f"Parsed order parameters for {sym}: Entry=₹{entry_price} (User Req: {order_type} @ ₹{price}), "
            f"Target=₹{target_val} (User Req: ₹{target_price}), SL=₹{sl_val} (User Req: ₹{stop_loss_1})"
        )

        is_super_order_placed = False
        buy_order_id = None
        sl_order_id = None
        target_order_id = None
        sl_remarks = ""
        target_remarks = ""

        # PRIMARY: Solution B - Dhan Native Super Order (Bracket Order with Entry, Target & SL)
        # Groups all 3 legs into a single ticket, guaranteeing ZERO extra short-sell margin deduction!
        if product_type == "INTRADAY" and entry_price > 0 and target_val > entry_price and sl_val < entry_price:
            try:
                logger.info(f"Submitting Dhan Super Order (Bracket): {sym} Entry=₹{entry_price} Target=₹{target_val} SL=₹{sl_val}")
                super_resp = self.dhan_client.place_super_order(
                    security_id=str(sec_id),
                    exchange_segment=dhan_exch,
                    transaction_type=self.dhan_client.BUY,
                    quantity=quantity,
                    order_type=self.dhan_client.LIMIT,
                    product_type=dhan_prod,
                    price=entry_price,
                    targetPrice=target_val,
                    stopLossPrice=sl_val,
                    tag=f"apx_{int(time.time())}"
                )
                logger.info(f"Dhan Super Order response: {super_resp}")
                if super_resp.get("status") == "success":
                    buy_order_id = str(super_resp.get("data", {}).get("orderId") or "DHAN_SUPER_ORD")
                    sl_order_id = f"super_sl_{buy_order_id}"
                    target_order_id = f"super_tgt_{buy_order_id}"
                    sl_remarks = f"Native Bracket Stop-Loss Active (Super Order ID: {buy_order_id})"
                    target_remarks = f"Native Bracket Exit Target Active (Super Order ID: {buy_order_id})"
                    is_super_order_placed = True
                else:
                    logger.warning(f"Dhan Super Order rejected: {super_resp}. Falling back to standard entry + SL.")
            except Exception as e_super:
                logger.warning(f"place_super_order not supported for {sym}: {e_super}. Falling back to standard entry + SL.")

        # FALLBACK: If Super Order not supported or failed, place Entry BUY + real exchange Stop-Loss (SL) on Dhan.
        # CRITICAL: Never send a second unlinked standalone SELL Target order to exchange when margin is low,
        # because Dhan treats it as a separate Short-Sell! Instead, Target is monitored by System 2 Guardian!
        if not is_super_order_placed:
            buy_resp = self.dhan_client.place_order(
                security_id=str(sec_id),
                exchange_segment=dhan_exch,
                transaction_type=self.dhan_client.BUY,
                quantity=quantity,
                order_type=dhan_order_type,
                product_type=dhan_prod,
                price=entry_price,
                validity='DAY'
            )
            logger.info(f"Dhan standard BUY response: {buy_resp}")
            if buy_resp.get("status") != "success":
                err_msg = str(buy_resp.get("remarks") or buy_resp.get("message") or "Order rejected by Dhan.")
                # If Dhan rejected due to IP mismatch/whitelist, auto-register current IP immediately and retry!
                if "ip" in err_msg.lower():
                    logger.info(f"Dhan IP error detected: {err_msg}. Attempting immediate auto-registration...")
                    try:
                        from app.engine.dhan_ip_service import dhan_ip_service
                        ip_sync = dhan_ip_service.check_and_sync_ip(force=True)
                        if ip_sync.get("ordersAllowed"):
                            logger.info(f"IP auto-registered successfully ({ip_sync.get('currentIP')})! Retrying BUY order...")
                            time.sleep(0.5)
                            buy_resp = self.dhan_client.place_order(
                                security_id=str(sec_id),
                                exchange_segment=dhan_exch,
                                transaction_type=self.dhan_client.BUY,
                                quantity=quantity,
                                order_type=dhan_order_type,
                                product_type=dhan_prod,
                                price=entry_price,
                                validity='DAY'
                            )
                            logger.info(f"Dhan retry BUY response: {buy_resp}")
                            if buy_resp.get("status") == "success":
                                err_msg = ""
                    except Exception as e_retry:
                        logger.warning(f"Error during automatic IP registration & retry: {e_retry}")

                if buy_resp.get("status") != "success":
                    raise RuntimeError(f"Dhan Order Rejected: {err_msg}")

            buy_order_id = str(buy_resp.get("data", {}).get("orderId") or "DHAN_ORD")

            # Place genuine exchange-level Stop-Loss (SL) order on Dhan
            if sl_val > 0:
                try:
                    sl_trigger_price = sl_val
                    sl_limit_price = round(round((sl_val * 0.995) / 0.05) * 0.05, 2)
                    if sl_limit_price >= sl_trigger_price:
                        sl_limit_price = round(sl_trigger_price - 0.05, 2)

                    logger.info(f"Submitting exchange Stop-Loss (SL) to Dhan at Trigger=₹{sl_trigger_price}, Limit=₹{sl_limit_price}")
                    sl_resp = self.dhan_client.place_order(
                        security_id=str(sec_id),
                        exchange_segment=dhan_exch,
                        transaction_type=self.dhan_client.SELL,
                        quantity=quantity,
                        order_type=self.dhan_client.SL,
                        product_type=dhan_prod,
                        price=sl_limit_price,
                        trigger_price=sl_trigger_price,
                        validity='DAY'
                    )
                    logger.info(f"Dhan SL order response: {sl_resp}")
                    if sl_resp.get("status") == "success":
                        sl_order_id = str(sl_resp.get("data", {}).get("orderId"))
                        sl_remarks = f"Exchange Stop-Loss Active on NSE/BSE (SL Order ID: {sl_order_id})"
                    else:
                        sl_remarks = f"Notice: SL placement rejected by Dhan: {sl_resp.get('remarks')}"
                except Exception as ex:
                    logger.error(f"Failed to place native exchange stop-loss on Dhan: {ex}")
                    sl_remarks = f"Stop-loss error: {ex}"

            # Target is monitored server-side by Guardian (avoids double short-sell margin rejection!)
            if target_val > 0:
                target_remarks = f"Guardian Auto-Target Active at ₹{target_val} (Zero-margin OCO protection)"

        # Record mapping so we can manage SL & Target on square-off / breakeven
        self._update_order_sl_tracker(sym, {
            "symbol": sym,
            "security_id": str(sec_id),
            "exchange_segment": exchange_segment,
            "quantity": quantity,
            "buy_order_id": buy_order_id,
            "sl_order_id": sl_order_id,
            "target_order_id": target_order_id,
            "stop_loss_1": sl_val if sl_val > 0 else stop_loss_1,
            "stop_loss_2": conditional_stop_2,
            "target_price": target_val if target_val > 0 else target_price,
            "placed_at": datetime.now(IST).strftime("%d %b %Y, %I:%M %p")
        })

        return {
            "status": "SUCCESS",
            "message": f"Order sent to Dhan. {sl_remarks} {target_remarks}".strip(),
            "order_id": buy_order_id,
            "sl_order_id": sl_order_id,
            "target_order_id": target_order_id,
            "symbol": sym,
            "quantity": quantity,
            "price": entry_price if entry_price > 0 else price,
            "stop_loss_1": sl_val if sl_val > 0 else stop_loss_1,
            "conditional_stop_2": conditional_stop_2,
            "target_price": target_val if target_val > 0 else target_price
        }

    # ---------------------------------------------------------
    # 5. 1-CLICK SQUARE-OFF / SELL WITH AUTOMATIC SL CANCELLATION
    # ---------------------------------------------------------
    def square_off_position(self, position_id: str, quantity: Optional[int] = None, symbol: Optional[str] = None) -> Dict[str, Any]:
        """
        Instantly sells position on Dhan at Market and cancels the pending
        Stop-Loss & Exit Target orders on the exchange so no orphaned short orders remain.
        """
        if not self.dhan_client:
            self._init_dhan_client()

        if not self.dhan_client:
            raise RuntimeError("Dhan trading client is not connected.")

        # Find position
        positions = self.get_open_positions()
        target_pos = None
        for p in positions:
            if p.get("position_id") == position_id or (symbol and p.get("symbol") == symbol.upper()):
                target_pos = p
                break

        if not target_pos:
            raise RuntimeError("Active position not found in your Dhan account.")

        sym = target_pos["symbol"]
        sec_id = target_pos.get("security_id")
        qty_to_sell = quantity or target_pos["quantity"]
        exch_seg = target_pos.get("exchange_segment", "NSE_EQ")
        dhan_exch = self.dhan_client.NSE if "NSE" in exch_seg.upper() else self.dhan_client.BSE
        dhan_prod = self.dhan_client.INTRA if target_pos.get("product_type") == "INTRADAY" else self.dhan_client.CNC

        # Step 1: Submit Market Sell order to Dhan
        logger.info(f"Submitting market square-off to Dhan for {sym} Qty={qty_to_sell}")
        sell_resp = self.dhan_client.place_order(
            security_id=str(sec_id),
            exchange_segment=dhan_exch,
            transaction_type=self.dhan_client.SELL,
            quantity=qty_to_sell,
            order_type=self.dhan_client.MARKET,
            product_type=dhan_prod,
            price=0.0,
            validity='DAY'
        )

        if sell_resp.get("status") != "success":
            err = str(sell_resp.get("remarks") or "Square-off rejected by Dhan.")
            raise RuntimeError(f"Square-off failed: {err}")

        # Step 2: Automatically cancel any pending Stop-Loss & Target orders for this position on Dhan
        tracker = self._load_order_sl_tracker()
        sl_info = tracker.get(sym, {})
        sl_order_id = sl_info.get("sl_order_id")
        target_order_id = sl_info.get("target_order_id")

        if sl_order_id:
            try:
                logger.info(f"Canceling pending Stop-Loss order {sl_order_id} on Dhan exchange")
                self.dhan_client.cancel_order(order_id=sl_order_id)
            except Exception as e:
                logger.warning(f"Notice on canceling SL order {sl_order_id}: {e}")

        if target_order_id:
            try:
                logger.info(f"Canceling pending Exit Target order {target_order_id} on Dhan exchange")
                self.dhan_client.cancel_order(order_id=target_order_id)
            except Exception as e:
                logger.warning(f"Notice on canceling Target order {target_order_id}: {e}")

        # Remove from active tracker
        if sym in tracker:
            del tracker[sym]
            self._save_order_sl_tracker(tracker)

        return {
            "status": "SUCCESS",
            "message": f"Successfully squared off {qty_to_sell} shares of {sym} on Dhan. Exchange orders cancelled.",
            "sell_order_id": sell_resp.get("data", {}).get("orderId")
        }

    # ---------------------------------------------------------
    # Internal Order SL Correlation Tracker
    # ---------------------------------------------------------
    def _load_order_sl_tracker(self) -> Dict[str, Any]:
        if os.path.exists(ORDER_TRACKER_FILE):
            try:
                with open(ORDER_TRACKER_FILE, "r") as f:
                    return json.load(f)
            except Exception:
                pass
        return {}

    def _save_order_sl_tracker(self, data: Dict[str, Any]):
        try:
            with open(ORDER_TRACKER_FILE, "w") as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            logger.error(f"Error saving SL tracker: {e}")

    def _update_order_sl_tracker(self, symbol: str, entry: Dict[str, Any]):
        tracker = self._load_order_sl_tracker()
        tracker[symbol.upper()] = entry
        self._save_order_sl_tracker(tracker)

dhan_trade_service = DhanTradeService()
