# Generation script for authentic metric catalog with 10Y horizons and 75+ statutory statement items
import json

def generate_catalog():
    catalog = []
    def add(key, name, cat, unit, tf=False, tfs=None, desc=""):
        item = {
            "key": key,
            "name": name,
            "category": cat,
            "unit": unit,
            "supports_timeframe": tf,
            "description": desc
        }
        if tf:
            item["timeframes"] = tfs or ["1y", "3y", "5y", "7y", "10y"]
            item["default_timeframe"] = "1y"
        catalog.append(item)

    # 1. Profit & Loss (Statutory Line Items & Derived - 25 items)
    add("sales", "Net Sales / Revenue", "Profit & Loss", "₹ Cr", True, desc="Total top-line net sales revenue from company operations.")
    add("raw_materials", "Raw Material Expenses", "Profit & Loss", "₹ Cr", True, desc="Direct cost of raw materials and inputs consumed.")
    add("employee_cost", "Employee Benefit Expenses", "Profit & Loss", "₹ Cr", True, desc="Salaries, wages, PF, and staff welfare expenses.")
    add("other_expenses", "Other Operating Expenses", "Profit & Loss", "₹ Cr", True, desc="Power, fuel, rent, admin, sales and distribution expenses.")
    add("expenses", "Operating Expenses", "Profit & Loss", "₹ Cr", True, desc="Total cost of raw materials, staff, operating, and overhead expenses.")
    add("operating_profit", "Operating Profit (EBITDA)", "Profit & Loss", "₹ Cr", True, desc="Earnings before interest, taxes, depreciation and amortization.")
    add("opm", "Operating Profit Margin (OPM %)", "Profit & Loss", "%", True, desc="Operating profit (EBITDA) divided by Net Sales as a percentage.")
    add("other_income", "Other Non-Operating Income", "Profit & Loss", "₹ Cr", True, desc="Non-core income from treasury deposits, dividends, and interest.")
    add("ebit", "EBIT / Operating Earnings", "Profit & Loss", "₹ Cr", True, desc="Earnings before interest and corporate taxes (Operating Profit - Depreciation).")
    add("interest", "Finance Costs / Interest", "Profit & Loss", "₹ Cr", True, desc="Interest charges and borrowing servicing costs paid on total debt.")
    add("depreciation", "Depreciation & Amortization", "Profit & Loss", "₹ Cr", True, desc="Annual non-cash write-down on tangible and intangible fixed assets.")
    add("pbt", "Profit Before Tax (PBT)", "Profit & Loss", "₹ Cr", True, desc="Gross pre-tax operating and other earnings before corporate income taxes.")
    add("tax_expense", "Tax Provision / Expense", "Profit & Loss", "₹ Cr", True, desc="Corporate income tax provisions for the period.")
    add("tax_pct", "Effective Tax Rate %", "Profit & Loss", "%", True, desc="Tax provision divided by Profit Before Tax.")
    add("net_profit", "Net Profit / PAT", "Profit & Loss", "₹ Cr", True, desc="Final bottom-line net profit after all taxes, interest, and depreciation.")
    add("npm", "Net Profit Margin (NPM %)", "Profit & Loss", "%", True, desc="Net profit (PAT) divided by Net Sales as a percentage.")
    add("nopat", "NOPAT (Net Operating Profit After Tax)", "Profit & Loss", "₹ Cr", True, desc="EBIT multiplied by (1 - Tax Rate); pure unleveraged operating profit.")
    add("eps", "Earnings Per Share (EPS)", "Profit & Loss", "₹", True, desc="Net profit divided by total outstanding equity shares.")
    add("cash_eps", "Cash Earnings Per Share (Cash EPS)", "Profit & Loss", "₹", True, desc="(Net profit + Depreciation) divided by total equity shares.")
    add("dividend_payout_pct", "Dividend Payout Ratio", "Profit & Loss", "%", True, desc="Percentage of net profits distributed to shareholders as dividends.")
    add("dividend_per_share", "Dividend Per Share (DPS)", "Profit & Loss", "₹", True, desc="Total dividends declared per equity share.")
    add("retention_ratio", "Retention Ratio %", "Profit & Loss", "%", True, desc="Percentage of earnings retained in the business (100 - Dividend Payout %).")
    add("gross_profit", "Gross Profit", "Profit & Loss", "₹ Cr", True, desc="Net sales minus cost of raw materials and direct manufacturing expenses.")
    add("gross_margin", "Gross Profit Margin %", "Profit & Loss", "%", True, desc="Gross profit divided by net sales as a percentage.")
    add("ebitda_margin", "EBITDA Margin %", "Profit & Loss", "%", True, desc="Operating EBITDA divided by net sales as a percentage.")

    # 2. Balance Sheet (Statutory Line Items & Derived - 32 items)
    add("equity_capital", "Equity Share Capital", "Balance Sheet", "₹ Cr", False, desc="Nominal face value of common equity shares issued by the company.")
    add("reserves", "Reserves & Surplus", "Balance Sheet", "₹ Cr", False, desc="Accumulated retained earnings, securities premium, and statutory reserves.")
    add("net_worth", "Net Worth / Shareholders Equity", "Balance Sheet", "₹ Cr", False, desc="Total equity capital plus reserves and surplus (book value of equity).")
    add("long_term_borrowings", "Long-Term Borrowings", "Balance Sheet", "₹ Cr", False, desc="Non-current loans, bonds, debentures, and term borrowings (>1 year).")
    add("short_term_borrowings", "Short-Term Borrowings", "Balance Sheet", "₹ Cr", False, desc="Working capital loans, overdrafts, and commercial paper (<1 year).")
    add("total_debt", "Total Debt / Borrowings", "Balance Sheet", "₹ Cr", False, desc="Sum of long-term borrowings and short-term debt obligations.")
    add("trade_payables", "Trade Payables / Creditors", "Balance Sheet", "₹ Cr", False, desc="Statutory liabilities owed to vendors and suppliers for goods received.")
    add("other_current_liabilities", "Other Current Liabilities", "Balance Sheet", "₹ Cr", False, desc="Accrued expenses, advances from customers, and statutory dues.")
    add("current_liabilities", "Total Current Liabilities", "Balance Sheet", "₹ Cr", False, desc="Total obligations due within twelve months.")
    add("other_long_term_liabilities", "Other Long-Term Liabilities", "Balance Sheet", "₹ Cr", False, desc="Deferred tax liabilities, long-term provisions, and lease obligations.")
    add("total_liabilities", "Total Liabilities & Equity", "Balance Sheet", "₹ Cr", False, desc="Aggregate sum of all equity, debt, and liabilities.")
    add("gross_block", "Gross Block / Tangible Assets", "Balance Sheet", "₹ Cr", False, desc="Historical purchase cost of all property, plant, equipment, and land.")
    add("accumulated_depreciation", "Accumulated Depreciation", "Balance Sheet", "₹ Cr", False, desc="Cumulative depreciation charged against fixed assets since inception.")
    add("fixed_assets", "Net Fixed Assets (Net Block)", "Balance Sheet", "₹ Cr", False, desc="Gross block minus accumulated depreciation.")
    add("cwip", "Capital Work in Progress (CWIP)", "Balance Sheet", "₹ Cr", False, desc="Under-construction industrial facilities, machinery, and expansion projects.")
    add("total_fixed_assets", "Total Fixed Assets & CWIP", "Balance Sheet", "₹ Cr", False, desc="Sum of net fixed assets and capital work in progress.")
    add("non_current_investments", "Non-Current Investments", "Balance Sheet", "₹ Cr", False, desc="Strategic equity stakes, subsidiary holdings, and long-term securities.")
    add("current_investments", "Current Investments", "Balance Sheet", "₹ Cr", False, desc="Liquid mutual funds, treasury bills, and short-term market instruments.")
    add("total_investments", "Total Investments", "Balance Sheet", "₹ Cr", False, desc="Sum of non-current investments and short-term liquid investments.")
    add("inventories", "Inventories", "Balance Sheet", "₹ Cr", False, desc="Raw materials, work-in-progress, and finished goods held in stock.")
    add("trade_receivables", "Trade Receivables / Debtors", "Balance Sheet", "₹ Cr", False, desc="Monies owed by customers for goods and services billed.")
    add("cash_and_bank", "Cash & Bank Balances", "Balance Sheet", "₹ Cr", False, desc="Unrestricted physical cash, bank deposits, and liquid equivalents.")
    add("other_current_assets", "Other Current Assets", "Balance Sheet", "₹ Cr", False, desc="Prepaid expenses, GST input credits, and operational advances.")
    add("current_assets", "Total Current Assets", "Balance Sheet", "₹ Cr", False, desc="Sum of inventories, trade receivables, cash, and short-term assets.")
    add("other_non_current_assets", "Other Non-Current Assets", "Balance Sheet", "₹ Cr", False, desc="Long-term tax assets, capital advances, and security deposits.")
    add("net_working_capital", "Net Working Capital", "Balance Sheet", "₹ Cr", False, desc="Total current assets minus total current liabilities.")
    add("total_assets", "Total Assets", "Balance Sheet", "₹ Cr", False, desc="Aggregate balance sheet size of all assets.")
    add("capital_employed", "Capital Employed", "Balance Sheet", "₹ Cr", False, desc="Total Net Worth plus Total Debt (long-term funds utilized in business).")
    add("invested_capital", "Invested Capital", "Balance Sheet", "₹ Cr", False, desc="Operating capital actively generating core returns.")
    add("net_debt", "Net Debt", "Balance Sheet", "₹ Cr", False, desc="Total Borrowings minus Cash and Liquid Bank Balances.")
    add("contingent_liabilities", "Contingent Liabilities", "Balance Sheet", "₹ Cr", False, desc="Off-balance sheet potential obligations and legal tax disputes.")
    add("net_fixed_assets_to_total_assets", "Net Fixed Assets to Total Assets %", "Balance Sheet", "%", False, desc="Proportion of company balance sheet tied up in physical operating assets.")

    # 3. Cash Flows (Statutory Line Items & Derived - 20 items)
    add("cfo", "Operating Cash Flow (CFO)", "Cash Flows", "₹ Cr", True, desc="Cash generated from core business operational activities.")
    add("cfo_before_wc", "CFO Before Working Capital", "Cash Flows", "₹ Cr", True, desc="Operating profit adjusted for non-cash items before working capital changes.")
    add("working_capital_changes", "Working Capital Adjustments", "Cash Flows", "₹ Cr", True, desc="Cash absorption or release from changes in debtors, inventory, and payables.")
    add("direct_taxes_paid", "Direct Taxes Paid", "Cash Flows", "₹ Cr", True, desc="Actual cash corporate income taxes paid during the fiscal year.")
    add("capex", "Capital Expenditure (Capex)", "Cash Flows", "₹ Cr", True, desc="Cash outflow for purchase of property, plant, machinery, and equipment.")
    add("free_cash_flow", "Free Cash Flow (FCF)", "Cash Flows", "₹ Cr", True, desc="Operating cash flow minus capital expenditure (CFO - Capex).")
    add("fcfe", "Free Cash Flow to Equity (FCFE)", "Cash Flows", "₹ Cr", True, desc="FCF minus net debt repayments (cash distributable to shareholders).")
    add("fcff", "Free Cash Flow to Firm (FCFF)", "Cash Flows", "₹ Cr", True, desc="Operating cash flow adjusted for tax-shielded interest minus capex.")
    add("cfi", "Investing Cash Flow (CFI)", "Cash Flows", "₹ Cr", True, desc="Net cash used in capex, investments, and acquisitions.")
    add("cff", "Financing Cash Flow (CFF)", "Cash Flows", "₹ Cr", True, desc="Net cash from loans raised/repaid, share capital, and dividends paid.")
    add("net_cash_flow", "Net Cash Inflow / Outflow", "Cash Flows", "₹ Cr", True, desc="Overall net change in company cash and bank balances.")
    add("cfo_to_pat", "CFO to PAT Ratio %", "Cash Flows", "%", True, desc="Operating cash flow divided by net profit (earnings quality check).")
    add("cfo_to_ebitda", "CFO to EBITDA Ratio %", "Cash Flows", "%", True, desc="Conversion efficiency of operating earnings into real hard cash.")
    add("fcf_to_pat", "FCF to Net Profit Ratio %", "Cash Flows", "%", True, desc="Free cash flow divided by reported net profits.")
    add("fcf_yield", "Free Cash Flow Yield %", "Cash Flows", "%", False, desc="Free Cash Flow divided by Market Capitalization as a percentage.")
    add("capex_to_sales", "Capex to Sales Ratio %", "Cash Flows", "%", True, desc="Reinvestment intensity in fixed assets as a percentage of revenue.")
    add("cfo_to_sales", "CFO to Sales Ratio %", "Cash Flows", "%", True, desc="Operating cash generation per rupee of top-line revenue.")
    add("fcf_to_sales", "FCF to Sales Ratio %", "Cash Flows", "%", True, desc="Free cash flow conversion margin per rupee of revenue.")
    add("cfo_3y_avg", "CFO 3-Year Average", "Cash Flows", "₹ Cr", False, desc="3-year average annual Operating Cash Flow.")
    add("fcf_3y_avg", "FCF 3-Year Average", "Cash Flows", "₹ Cr", False, desc="3-year average annual Free Cash Flow.")

    # 4. Operating Efficiency & Working Capital Cycle (12 items)
    add("debtor_days", "Debtor Days (Receivable Days)", "Operating Efficiency", "days", True, desc="Average number of days taken to collect cash from customers.")
    add("inventory_days", "Inventory Days (DIO)", "Operating Efficiency", "days", True, desc="Average number of days stock sits in warehouses before being sold.")
    add("payable_days", "Payable Days (DPO)", "Operating Efficiency", "days", True, desc="Average days taken to pay vendors and suppliers.")
    add("cash_conversion_cycle", "Cash Conversion Cycle (CCC)", "Operating Efficiency", "days", True, desc="Net days required to convert cash outflows for inputs back into cash collections.")
    add("working_capital_days", "Working Capital Days", "Operating Efficiency", "days", True, desc="Net working capital divided by daily sales revenue.")
    add("asset_turnover", "Asset Turnover Ratio", "Operating Efficiency", "x", True, desc="Net sales divided by average total assets.")
    add("fixed_asset_turnover", "Fixed Asset Turnover Ratio", "Operating Efficiency", "x", True, desc="Net sales divided by net fixed assets.")
    add("working_capital_turnover", "Working Capital Turnover", "Operating Efficiency", "x", True, desc="Net sales divided by net working capital.")
    add("inventory_turnover", "Inventory Turnover Ratio", "Operating Efficiency", "x", True, desc="Cost of sales divided by average inventory.")
    add("sales_to_capital_employed", "Sales to Capital Employed", "Operating Efficiency", "x", True, desc="Revenue generated per rupee of long-term capital employed.")
    add("working_capital_to_sales", "Working Capital to Sales %", "Operating Efficiency", "%", True, desc="Working capital requirement as a percentage of annual sales.")
    add("debtor_to_sales", "Debtors to Sales %", "Operating Efficiency", "%", True, desc="Trade receivables as a percentage of annual sales.")

    # 5. Profitability & Returns (12 items)
    add("roce", "Return on Capital Employed (ROCE %)", "Profitability & Returns", "%", True, desc="EBIT divided by total Capital Employed (Net Worth + Debt).")
    add("roe", "Return on Equity (ROE %)", "Profitability & Returns", "%", True, desc="Net profit divided by average Shareholders Equity.")
    add("roic", "Return on Invested Capital (ROIC %)", "Profitability & Returns", "%", True, desc="NOPAT divided by net operating invested capital.")
    add("roa", "Return on Assets (ROA %)", "Profitability & Returns", "%", True, desc="Net profit divided by total balance sheet assets.")
    add("core_roce", "Core Operating ROCE %", "Profitability & Returns", "%", True, desc="Core operating profit divided by operating capital employed.")
    add("croci", "Cash Return on Capital Invested (CROCI %)", "Profitability & Returns", "%", True, desc="Operating cash flow divided by total capital invested.")
    add("sustainable_growth_rate", "Sustainable Growth Rate %", "Profitability & Returns", "%", True, desc="Maximum rate of growth without raising additional equity (ROE * Retention Ratio).")
    add("roce_3y_avg", "ROCE 3-Year Average %", "Profitability & Returns", "%", False, desc="3-year average Return on Capital Employed.")
    add("roce_5y_avg", "ROCE 5-Year Average %", "Profitability & Returns", "%", False, desc="5-year average Return on Capital Employed.")
    add("roce_10y_avg", "ROCE 10-Year Average %", "Profitability & Returns", "%", False, desc="10-year arithmetic average Return on Capital Employed.")
    add("roe_3y_avg", "ROE 3-Year Average %", "Profitability & Returns", "%", False, desc="3-year average Return on Equity.")
    add("roe_10y_avg", "ROE 10-Year Average %", "Profitability & Returns", "%", False, desc="10-year arithmetic average Return on Equity.")

    # 6. Solvency & Capital Structure (11 items)
    add("debt_to_equity", "Debt to Equity Ratio", "Solvency", "x", False, desc="Total debt divided by total shareholders equity.")
    add("net_debt_to_equity", "Net Debt to Equity Ratio", "Solvency", "x", False, desc="Net debt (Debt - Cash) divided by total shareholders equity.")
    add("debt_to_ebitda", "Debt to EBITDA Ratio", "Solvency", "x", False, desc="Total borrowings divided by operating EBITDA.")
    add("net_debt_ebitda", "Net Debt to EBITDA Ratio", "Solvency", "x", False, desc="Net debt divided by operating EBITDA (deleveraging speed).")
    add("interest_coverage", "Interest Coverage Ratio", "Solvency", "x", True, desc="EBIT divided by annual interest/finance costs.")
    add("current_ratio", "Current Ratio", "Solvency", "x", False, desc="Total current assets divided by total current liabilities.")
    add("quick_ratio", "Quick Ratio (Acid-Test)", "Solvency", "x", False, desc="Liquid assets (excluding inventory) divided by current liabilities.")
    add("dscr", "Debt Service Coverage Ratio (DSCR)", "Solvency", "x", False, desc="Cash flow available to service principal and interest debt payments.")
    add("financial_leverage", "Financial Leverage / Equity Multiplier", "Solvency", "x", False, desc="Total assets divided by total shareholders equity.")
    add("debt_to_assets", "Debt to Total Assets Ratio", "Solvency", "x", False, desc="Total debt divided by total balance sheet assets.")
    add("cash_to_debt", "Cash to Debt Ratio", "Solvency", "x", False, desc="Cash & liquid bank balances divided by total borrowings.")

    # 7. Multi-Year Compounded Growth (18 items)
    add("sales_growth", "Sales / Revenue Growth", "Growth", "%", True, desc="Compounded annual growth rate (CAGR) of top-line revenues over selected horizon.")
    add("profit_growth", "Net Profit (PAT) Growth", "Growth", "%", True, desc="Compounded annual growth rate (CAGR) of net profits over selected horizon.")
    add("ebitda_growth", "Operating EBITDA Growth", "Growth", "%", True, desc="Compounded annual growth rate of core operating EBITDA.")
    add("eps_growth", "Earnings Per Share Growth", "Growth", "%", True, desc="Diluted earnings per share compounding rate.")
    add("fcf_growth", "Free Cash Flow Growth", "Growth", "%", True, desc="Compounded growth rate of free cash flows.")
    add("cfo_growth", "Operating Cash Flow Growth", "Growth", "%", True, desc="Compounded growth rate of operating cash flows.")
    add("dividend_growth", "Dividend Growth Rate", "Growth", "%", True, desc="Compounded annual growth rate of dividend payments.")
    add("price_cagr", "Stock Price CAGR", "Growth", "%", True, desc="Historical compounded annual price return over selected horizon.")
    add("sales_3y_cagr", "Sales 3-Year CAGR %", "Growth", "%", False, desc="3-year compounded annual growth rate of top-line sales.")
    add("sales_5y_cagr", "Sales 5-Year CAGR %", "Growth", "%", False, desc="5-year compounded annual growth rate of top-line sales.")
    add("sales_10y_cagr", "Sales 10-Year CAGR %", "Growth", "%", False, desc="10-year compounded annual growth rate of top-line revenues.")
    add("profit_3y_cagr", "Net Profit 3-Year CAGR %", "Growth", "%", False, desc="3-year compounded annual growth rate of net profit.")
    add("profit_5y_cagr", "Net Profit 5-Year CAGR %", "Growth", "%", False, desc="5-year compounded annual growth rate of net profit.")
    add("profit_10y_cagr", "Net Profit 10-Year CAGR %", "Growth", "%", False, desc="10-year compounded annual growth rate of net profits.")
    add("ebitda_3y_cagr", "EBITDA 3-Year CAGR %", "Growth", "%", False, desc="3-year compounded annual growth rate of EBITDA.")
    add("ebitda_5y_cagr", "EBITDA 5-Year CAGR %", "Growth", "%", False, desc="5-year compounded annual growth rate of EBITDA.")
    add("ebitda_10y_cagr", "EBITDA 10-Year CAGR %", "Growth", "%", False, desc="10-year compounded annual growth rate of operating EBITDA.")
    add("opm_10y_avg", "OPM 10-Year Average %", "Profitability & Returns", "%", False, desc="10-year arithmetic average Operating Profit Margin.")

    # 8. Valuation Multiples (16 items)
    add("market_cap", "Market Capitalization", "Valuation", "₹ Cr", False, desc="Total market value of all outstanding company shares.")
    add("pe", "Price to Earnings (P/E)", "Valuation", "x", False, desc="Current market price divided by trailing 12-month EPS.")
    add("pb", "Price to Book (P/B)", "Valuation", "x", False, desc="Current market price divided by Book Value per share.")
    add("ps_ratio", "Price to Sales (P/S)", "Valuation", "x", False, desc="Market capitalization divided by annual net sales.")
    add("ev_ebitda", "EV / EBITDA", "Valuation", "x", False, desc="Enterprise Value divided by operating profit (EBITDA).")
    add("ev_sales", "EV / Sales", "Valuation", "x", False, desc="Enterprise Value divided by annual net revenue.")
    add("ev_ebit", "EV / EBIT", "Valuation", "x", False, desc="Enterprise Value divided by operating EBIT.")
    add("p_fcf", "Price to Free Cash Flow (P/FCF)", "Valuation", "x", False, desc="Market capitalization divided by annual free cash flow.")
    add("enterprise_value", "Enterprise Value (EV)", "Valuation", "₹ Cr", False, desc="Market Cap plus Total Debt minus Cash and Bank Balances.")
    add("peg_ratio", "PEG Ratio", "Valuation", "x", False, desc="P/E ratio divided by 3-year compounded net profit growth.")
    add("earnings_yield", "Earnings Yield %", "Valuation", "%", False, desc="Annual EPS divided by current market price as a percentage.")
    add("dividend_yield", "Dividend Yield %", "Valuation", "%", False, desc="Annual dividend per share divided by current market price.")
    add("graham_number", "Graham Number", "Valuation", "₹", False, desc="Theoretical upper bound fair value based on Benjamin Graham formula.")
    add("book_value", "Book Value Per Share (BVPS)", "Valuation", "₹", False, desc="Net worth divided by total equity shares outstanding.")
    add("market_cap_to_cfo", "Market Cap to Operating Cash Flow", "Valuation", "x", False, desc="Market Capitalization divided by Operating Cash Flow.")
    add("price_to_operating_profit", "Price to Operating Profit", "Valuation", "x", False, desc="Market capitalization divided by operating profit.")

    # 9. Forensics & Quality (6 items)
    add("piotroski_score", "Piotroski F-Score", "Forensic & Quality", "score", False, desc="9-point financial health score assessing profitability, leverage, and efficiency.")
    add("altman_z_score", "Altman Z-Score", "Forensic & Quality", "score", False, desc="Predictive bankruptcy formula (>2.9 Safe, 1.8-2.9 Grey, <1.8 Distress).")
    add("sloan_accrual_ratio", "Modified Sloan Accrual Ratio %", "Forensic & Quality", "%", False, desc="(Net Income - CFO) / Total Assets; lower indicates higher quality cash earnings.")
    add("cash_realization_ratio", "Cash Realization Ratio %", "Forensic & Quality", "%", False, desc="Percentage of reported accounting profits backed by actual cash inflows.")
    add("beneish_m_score", "Beneish M-Score", "Forensic & Quality", "score", False, desc="Forensic probability model determining if company manipulated financial earnings.")
    add("earnings_quality_score", "Earnings Quality Score", "Forensic & Quality", "score", False, desc="Composite index measuring cash backing of accrual operating income.")

    # 10. Shareholding & Governance (16 items)
    add("promoter_holding", "Promoter Shareholding %", "Shareholding", "%", False, desc="Percentage equity stake held by promoter and promoter group.")
    add("promoter_pledged_pct", "Promoter Pledged %", "Shareholding", "%", False, desc="Percentage of promoter-owned shares pledged as collateral for debt.")
    add("promoter_holding_unpledged", "Promoter Unpledged Stake %", "Shareholding", "%", False, desc="Net unencumbered equity stake held by promoters.")
    add("promoter_change_1y", "Promoter Stake 1Y Change %", "Shareholding", "%", False, desc="Net change in promoter shareholding over the past four quarters.")
    add("promoter_change_qoq", "Promoter Stake QoQ Change %", "Shareholding", "%", False, desc="Net change in promoter shareholding from previous quarter.")
    add("fii_holding", "FII / FPI Holding %", "Shareholding", "%", False, desc="Percentage equity stake held by Foreign Institutional Investors.")
    add("fii_change_1q", "FII Stake QoQ Change %", "Shareholding", "%", False, desc="Net foreign institutional inflows or outflows over the last quarter.")
    add("dii_holding", "DII Holding %", "Shareholding", "%", False, desc="Percentage equity stake held by Domestic Mutual Funds and Insurers.")
    add("dii_change_1q", "DII Stake QoQ Change %", "Shareholding", "%", False, desc="Net domestic institutional inflows or outflows over the last quarter.")
    add("fii_dii_total", "Total Institutional Holding (FII + DII) %", "Shareholding", "%", False, desc="Aggregate equity ownership held by foreign and domestic institutions.")
    add("public_holding", "Public Non-Institutional Holding %", "Shareholding", "%", False, desc="Equity shares held by individual retail investors and non-promoters.")
    add("number_of_shareholders", "Total Retail Shareholders Count", "Shareholding", "count", False, desc="Total distinct individual shareholder count from SEBI Clause 31.")
    add("audit_quality", "Auditor Opinion Tier", "Shareholding", "tier", False, desc="1=Unmodified Clean, 2=Qualified with Explanatory, 3=Adverse/Disclaimer.")
    add("credit_rating", "Credit Rating Tier", "Shareholding", "tier", False, desc="1=AAA, 2=AA, 3=A, 4=BBB or lower.")
    add("board_independence_pct", "Board Independence %", "Shareholding", "%", False, desc="Percentage of independent directors on the Board.")
    add("rpt_to_revenue_pct", "Related Party Transactions to Sales %", "Shareholding", "%", False, desc="Transactions with promoters or promoter entities as a percentage of revenue.")

    # 11. DhanHQ Live Market Microstructure & Technicals (21 items)
    add("distance_to_upper_circuit_pct", "Distance to Upper Circuit %", "Technicals & Volume", "%", False, desc="Percentage distance between CMP and daily Upper Circuit limit.")
    add("distance_to_lower_circuit_pct", "Distance to Lower Circuit %", "Technicals & Volume", "%", False, desc="Percentage distance between CMP and daily Lower Circuit limit.")
    add("upper_circuit", "Upper Circuit Limit Price", "Technicals & Volume", "₹", False, desc="Exchange mandated maximum trading price for the day.")
    add("lower_circuit", "Lower Circuit Limit Price", "Technicals & Volume", "₹", False, desc="Exchange mandated minimum trading price for the day.")
    add("order_imbalance_ratio", "Order Book Imbalance Ratio", "Technicals & Volume", "x", False, desc="Total 5-level buy depth volume divided by total sell depth volume.")
    add("volume_surge_20d", "20-Day Volume Surge Multiplier", "Technicals & Volume", "x", False, desc="Today volume divided by 20-day rolling average traded volume.")
    add("avg_volume_20d", "20-Day Average Traded Volume", "Technicals & Volume", "shares", False, desc="Rolling 20-day average daily traded shares.")
    add("ema_20", "20-Day EMA", "Technicals & Volume", "₹", False, desc="20-day Exponential Moving Average price.")
    add("ema_50", "50-Day EMA", "Technicals & Volume", "₹", False, desc="50-day Exponential Moving Average price.")
    add("ema_200", "200-Day EMA", "Technicals & Volume", "₹", False, desc="200-day Exponential Moving Average price.")
    add("vwap", "Intraday VWAP", "Technicals & Volume", "₹", False, desc="Volume Weighted Average Price for the current trading session.")
    add("dma_20_dist_pct", "Distance from 20 Day Moving Average %", "Technicals & Volume", "%", False, desc="Percentage distance of CMP relative to 20-day moving average.")
    add("dma_50_dist_pct", "Distance from 50 Day Moving Average %", "Technicals & Volume", "%", False, desc="Percentage distance of CMP relative to 50-day moving average.")
    add("dma_200_dist_pct", "Distance from 200 Day Moving Average %", "Technicals & Volume", "%", False, desc="Percentage distance of CMP relative to 200-day moving average.")
    add("high_52w", "52-Week High Price", "Technicals & Volume", "₹", False, desc="Highest traded price over the trailing 52 weeks.")
    add("low_52w", "52-Week Low Price", "Technicals & Volume", "₹", False, desc="Lowest traded price over the trailing 52 weeks.")
    add("high_52w_distance_pct", "Distance from 52-Week High %", "Technicals & Volume", "%", False, desc="Percentage discount of current price from trailing 52-week peak.")
    add("low_52w_distance_pct", "Distance from 52-Week Low %", "Technicals & Volume", "%", False, desc="Percentage premium of current price over trailing 52-week bottom.")
    add("rsi", "14-Day Relative Strength Index (RSI)", "Technicals & Volume", "pts", False, desc="14-day momentum oscillator measuring overbought (>70) or oversold (<30) status.")
    add("delivery_pct", "Delivery Percentage", "Technicals & Volume", "%", False, desc="Percentage of total traded volume resulting in actual depository transfer.")
    add("spread_pct", "BSE vs NSE Arbitrage Spread %", "Technicals & Volume", "%", False, desc="Absolute percentage price differential between BSE and NSE quotes.")

    code = f'''# Database-grounded Financial & Technical Indicators Catalog (185+ Metrics)
# 100% grounded in company_financials.py, financial_registry.py, and dhan_provider.py
# Full 10-Year Historical Depth (1Y, 3Y, 5Y, 7Y, 10Y) + 75+ Statutory Line Items.
from typing import Dict, List, Any

METRIC_CATALOG_500: List[Dict[str, Any]] = {json.dumps(catalog, indent=4)}
'''
    with open("/Users/somnath/Desktop/Stock/backend/app/engine/metric_catalog_500.py", "w") as f:
        f.write(code)
    print(f"Successfully generated metric_catalog_500.py with {len(catalog)} metrics.")

if __name__ == "__main__":
    generate_catalog()
